export enum RoleName {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  FINANCE = "FINANCE",
  ACCOUNTANT = "ACCOUNTANT",
  TAX_CONSULTANT = "TAX_CONSULTANT",
  SUPPORT = "SUPPORT",
  READ_ONLY = "READ_ONLY"
}

export enum PermissionAction {
  VIEW = "VIEW",
  CREATE = "CREATE",
  EDIT = "EDIT",
  DELETE = "DELETE",
  UPLOAD = "UPLOAD",
  DOWNLOAD = "DOWNLOAD",
  APPROVE = "APPROVE",
  MANAGE_USERS = "MANAGE_USERS"
}

export enum ReportType {
  FINANCIAL_STATEMENT = "FINANCIAL_STATEMENT",
  PROFIT_AND_LOSS = "PROFIT_AND_LOSS",
  BALANCE_SHEET = "BALANCE_SHEET",
  CASH_FLOW = "CASH_FLOW",
  TRIAL_BALANCE = "TRIAL_BALANCE",
  VAT = "VAT",
  PAYE = "PAYE",
  CORPORATION_TAX = "CORPORATION_TAX",
  RECEIPT = "RECEIPT",
  INVOICE = "INVOICE",
  DRAFT = "DRAFT",
  CUSTOM = "CUSTOM"
}

export enum ReportSource {
  QUICKBOOKS = "QUICKBOOKS",
  MANUAL = "MANUAL",
  DRAFT = "DRAFT"
}

export enum DocumentCategory {
  FINANCIAL_STATEMENT = "FINANCIAL_STATEMENT",
  INVOICE = "INVOICE",
  RECEIPT = "RECEIPT",
  EXCEL = "EXCEL",
  PDF = "PDF",
  DRAFT = "DRAFT",
  TAX_REPORT = "TAX_REPORT",
  SUPPORTING = "SUPPORTING",
  EMPLOYEE_RECORD = "EMPLOYEE_RECORD",
  PAYSLIP = "PAYSLIP",
  PAYROLL_REPORT = "PAYROLL_REPORT",
  OTHER = "OTHER"
}

export enum InvoiceRequestStatus {
  PENDING_REVIEW = "PENDING_REVIEW",
  IN_PROGRESS = "IN_PROGRESS",
  FULFILLED = "FULFILLED",
  REJECTED = "REJECTED"
}

export enum InvoiceStatus {
  DRAFT = "DRAFT",
  SENT = "SENT",
  PAID = "PAID",
  VOID = "VOID"
}

export enum EmployeeStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE"
}

export enum PayrollRunStatus {
  DRAFT = "DRAFT",
  CALCULATED = "CALCULATED",
  APPROVED = "APPROVED",
  DISTRIBUTED = "DISTRIBUTED"
}

export enum ProductStatus {
  ACTIVE = "ACTIVE",
  ARCHIVED = "ARCHIVED"
}

export enum StockMovementReason {
  SALE = "SALE",
  RESTOCK = "RESTOCK",
  ADJUSTMENT = "ADJUSTMENT"
}

export enum SalePaymentMethod {
  CASH = "CASH",
  MPESA = "MPESA"
}

export enum SalePaymentStatus {
  PENDING = "PENDING",
  PAID = "PAID",
  FAILED = "FAILED"
}

export enum NotificationType {
  PAYMENT_REMINDER = "PAYMENT_REMINDER",
  FILING_REMINDER = "FILING_REMINDER",
  COMPLETED_WORK = "COMPLETED_WORK",
  NEW_DOCUMENT = "NEW_DOCUMENT",
  ANNOUNCEMENT = "ANNOUNCEMENT"
}

export enum NotificationChannel {
  PORTAL = "PORTAL",
  WHATSAPP = "WHATSAPP",
  EMAIL = "EMAIL"
}

export enum TaxType {
  VAT = "VAT",
  PAYE = "PAYE",
  CORPORATION_TAX = "CORPORATION_TAX",
  NSSF = "NSSF",
  SHIF = "SHIF",
  HOUSING_LEVY = "HOUSING_LEVY",
  OTHER = "OTHER"
}

export enum TaxStatus {
  DUE = "DUE",
  PAID = "PAID",
  OUTSTANDING = "OUTSTANDING",
  PENALTY = "PENALTY"
}

export enum BusinessStatus {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  ARCHIVED = "ARCHIVED"
}

export enum BusinessRequestStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED"
}

export enum WhatsAppState {
  AWAITING_PHONE = "AWAITING_PHONE",
  AWAITING_OTP = "AWAITING_OTP",
  MAIN_MENU = "MAIN_MENU",
  SELECT_BUSINESS = "SELECT_BUSINESS",
  REPORTS_SELECT_RANGE = "REPORTS_SELECT_RANGE",
  REPORTS_SELECT_TYPE = "REPORTS_SELECT_TYPE",
  TAXES_MENU = "TAXES_MENU",
  INVOICES_MENU = "INVOICES_MENU",
  INVOICES_ACTION_MENU = "INVOICES_ACTION_MENU",
  INVOICE_REQUEST_CUSTOMER_NAME = "INVOICE_REQUEST_CUSTOMER_NAME",
  INVOICE_REQUEST_KRA_PIN = "INVOICE_REQUEST_KRA_PIN",
  INVOICE_REQUEST_ITEM = "INVOICE_REQUEST_ITEM",
  INVOICE_REQUEST_AMOUNT = "INVOICE_REQUEST_AMOUNT",
  INVOICE_REQUEST_CONFIRM = "INVOICE_REQUEST_CONFIRM",
  RECEIPTS_MENU = "RECEIPTS_MENU",
  PAYROLL_MENU = "PAYROLL_MENU",
  DOCUMENTS_MENU = "DOCUMENTS_MENU",
  NOTIFICATIONS_MENU = "NOTIFICATIONS_MENU",
  AI_CHAT = "AI_CHAT",
  ESCALATION = "ESCALATION"
}

export enum SyncStatus {
  PENDING = "PENDING",
  RUNNING = "RUNNING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED"
}
